
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action ArquivoAction;
	
	private global::Gtk.Action EditarAction;
	
	private global::Gtk.Action AbrirAction;
	
	private global::Gtk.Action SalvarAction;
	
	private global::Gtk.Action ArquivoAction1;
	
	private global::Gtk.Action EditarAction1;
	
	private global::Gtk.Action InserirAction;
	
	private global::Gtk.Action AutmatoAction;
	
	private global::Gtk.Action GramticaRegularAction;
	
	private global::Gtk.Action ExpressoRegularAction;
	
	private global::Gtk.Action AbrirAction1;
	
	private global::Gtk.Action AutomatoAction;
	
	private global::Gtk.Action SalvarAction1;
	
	private global::Gtk.Action AutomatoAction1;
	
	private global::Gtk.Action DeterminizarAutmatoAction;
	
	private global::Gtk.VBox vbox2;
	
	private global::Gtk.MenuBar menubar2;
	
	private global::Gtk.Notebook notebook1;
	
	private global::Gtk.ScrolledWindow scrolledwindow1;
	
	private global::Gtk.Label label2;
	
	private global::Gtk.Fixed fixed2;
	
	private global::Gtk.Label label4;
	
	private global::Gtk.Fixed fixed3;
	
	private global::Gtk.Label label5;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.ArquivoAction = new global::Gtk.Action ("ArquivoAction", global::Mono.Unix.Catalog.GetString ("Arquivo"), null, null);
		this.ArquivoAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Arquivo");
		w1.Add (this.ArquivoAction, null);
		this.EditarAction = new global::Gtk.Action ("EditarAction", global::Mono.Unix.Catalog.GetString ("Editar"), null, null);
		this.EditarAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Editar");
		w1.Add (this.EditarAction, null);
		this.AbrirAction = new global::Gtk.Action ("AbrirAction", global::Mono.Unix.Catalog.GetString ("Abrir"), null, null);
		this.AbrirAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Abrir");
		w1.Add (this.AbrirAction, null);
		this.SalvarAction = new global::Gtk.Action ("SalvarAction", global::Mono.Unix.Catalog.GetString ("Salvar"), null, null);
		this.SalvarAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Salvar");
		w1.Add (this.SalvarAction, null);
		this.ArquivoAction1 = new global::Gtk.Action ("ArquivoAction1", global::Mono.Unix.Catalog.GetString ("Arquivo"), null, null);
		this.ArquivoAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Arquivo");
		w1.Add (this.ArquivoAction1, null);
		this.EditarAction1 = new global::Gtk.Action ("EditarAction1", global::Mono.Unix.Catalog.GetString ("Editar"), null, null);
		this.EditarAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Editar");
		w1.Add (this.EditarAction1, null);
		this.InserirAction = new global::Gtk.Action ("InserirAction", global::Mono.Unix.Catalog.GetString ("Inserir"), null, null);
		this.InserirAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Inserir");
		w1.Add (this.InserirAction, null);
		this.AutmatoAction = new global::Gtk.Action ("AutmatoAction", global::Mono.Unix.Catalog.GetString ("Autômato"), null, null);
		this.AutmatoAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Autômato");
		w1.Add (this.AutmatoAction, null);
		this.GramticaRegularAction = new global::Gtk.Action ("GramticaRegularAction", global::Mono.Unix.Catalog.GetString ("Gramática Regular"), null, null);
		this.GramticaRegularAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Gramática Regular");
		w1.Add (this.GramticaRegularAction, null);
		this.ExpressoRegularAction = new global::Gtk.Action ("ExpressoRegularAction", global::Mono.Unix.Catalog.GetString ("Expressão Regular"), null, null);
		this.ExpressoRegularAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Expressão Regular");
		w1.Add (this.ExpressoRegularAction, null);
		this.AbrirAction1 = new global::Gtk.Action ("AbrirAction1", global::Mono.Unix.Catalog.GetString ("Abrir"), null, null);
		this.AbrirAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Abrir");
		w1.Add (this.AbrirAction1, null);
		this.AutomatoAction = new global::Gtk.Action ("AutomatoAction", global::Mono.Unix.Catalog.GetString ("Automato"), null, null);
		this.AutomatoAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Automato");
		w1.Add (this.AutomatoAction, null);
		this.SalvarAction1 = new global::Gtk.Action ("SalvarAction1", global::Mono.Unix.Catalog.GetString ("Salvar"), null, null);
		this.SalvarAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Salvar");
		w1.Add (this.SalvarAction1, null);
		this.AutomatoAction1 = new global::Gtk.Action ("AutomatoAction1", global::Mono.Unix.Catalog.GetString ("Automato"), null, null);
		this.AutomatoAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Automato");
		w1.Add (this.AutomatoAction1, null);
		this.DeterminizarAutmatoAction = new global::Gtk.Action ("DeterminizarAutmatoAction", global::Mono.Unix.Catalog.GetString ("Determinizar Autômato"), null, null);
		this.DeterminizarAutmatoAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Determinizar Autômato");
		w1.Add (this.DeterminizarAutmatoAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar2'><menu name='ArquivoAction1' action='ArquivoAction1'><menu name='AbrirAction1' action='AbrirAction1'><menuitem name='AutomatoAction' action='AutomatoAction'/></menu><menu name='SalvarAction1' action='SalvarAction1'><menuitem name='AutomatoAction1' action='AutomatoAction1'/></menu></menu><menu name='EditarAction1' action='EditarAction1'><menuitem name='DeterminizarAutmatoAction' action='DeterminizarAutmatoAction'/></menu><menu name='InserirAction' action='InserirAction'><menuitem name='AutmatoAction' action='AutmatoAction'/><menuitem name='GramticaRegularAction' action='GramticaRegularAction'/><menuitem name='ExpressoRegularAction' action='ExpressoRegularAction'/></menu></menubar></ui>");
		this.menubar2 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar2")));
		this.menubar2.Name = "menubar2";
		this.vbox2.Add (this.menubar2);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.menubar2]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.notebook1 = new global::Gtk.Notebook ();
		this.notebook1.CanFocus = true;
		this.notebook1.Name = "notebook1";
		this.notebook1.CurrentPage = 0;
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
		this.scrolledwindow1.CanFocus = true;
		this.scrolledwindow1.Name = "scrolledwindow1";
		this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		this.notebook1.Add (this.scrolledwindow1);
		// Notebook tab
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Autômato");
		this.notebook1.SetTabLabel (this.scrolledwindow1, this.label2);
		this.label2.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.fixed2 = new global::Gtk.Fixed ();
		this.fixed2.Name = "fixed2";
		this.fixed2.HasWindow = false;
		this.notebook1.Add (this.fixed2);
		global::Gtk.Notebook.NotebookChild w4 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.fixed2]));
		w4.Position = 1;
		// Notebook tab
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Gramática Regular");
		this.notebook1.SetTabLabel (this.fixed2, this.label4);
		this.label4.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.fixed3 = new global::Gtk.Fixed ();
		this.fixed3.Name = "fixed3";
		this.fixed3.HasWindow = false;
		this.notebook1.Add (this.fixed3);
		global::Gtk.Notebook.NotebookChild w5 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.fixed3]));
		w5.Position = 2;
		// Notebook tab
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Expressão Regular");
		this.notebook1.SetTabLabel (this.fixed3, this.label5);
		this.label5.ShowAll ();
		this.vbox2.Add (this.notebook1);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.notebook1]));
		w6.Position = 1;
		this.Add (this.vbox2);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 445;
		this.DefaultHeight = 306;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.AutmatoAction.Activated += new global::System.EventHandler (this.inserirAutomato);
		this.AutomatoAction.Activated += new global::System.EventHandler (this.OnAutomatoActionActivated);
		this.AutomatoAction1.Activated += new global::System.EventHandler (this.OnAutomatoAction1Activated);
		this.DeterminizarAutmatoAction.Activated += new global::System.EventHandler (this.OnDeterminizarAutmatoActionActivated);
	}
}
